# Generated by Django 5.2 on 2025-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0002_plan_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
